### DISCUSSION TITLE
[Share & Showcase] Dynamic CSS for Displaying Links on the Side.

### DISCUSSION THREAD

**Discussion by Moyf** [ahts4962/nav-link-header#9] [Show and tell]
Demostration:
![Image](https://github.com/user-attachments/assets/a87964dd-630b-439f-812e-b7b73a4c089c)

By default, the links will be positioned on the left side of the note instead of being displayed in a bar at the top. 
Additionally, if you reduce the width, the layout will dynamically adjust.  

Once the overall width of the window falls below a specific threshold (1200px), the links will revert to the top position to prevent obstructing the text in the notes.
![Image](https://github.com/user-attachments/assets/07c839b2-fe4c-4aac-91f1-62a96e480242)

You could also refer to this video:
https://github.com/user-attachments/assets/cf1da666-7c69-4494-b83c-65ae775544af

```css
/* Plugin: Nav Link Header */

/* Default styles - converting the container into a small box in top-left corner */
.workspace-leaf-content:not(:has(.weekly-note, .monthly-note, .yearly-note)) .nav-link-header-navigation {
    background-color: transparent !important;
    width: auto !important;
    position: absolute;
    /* Position below the toolbar */
    top: 40px; 
    left: 1em;
    /* Needs to be higher than Sticky Headings z-index */
    z-index: 3;

    .background {
        padding: 0px !important;
        margin: 0px !important;
        border: 0px !important;
        border-radius: 0.4em !important;
        background-color: transparent !important;
    }
}

/* Styles for screens wider than 1200px - vertical layout */
@media (min-width: 1200px) {
    .workspace-leaf-content:not(:has(.weekly-note, .monthly-note, .yearly-note)) .nav-link-header-navigation {
        /* Position below banner (320px or 25vh, whichever is larger) */
        top: max(25vh, 320px) !important;
        /* Adaptive width based on content area */
        max-width: calc(calc(100% - var(--file-line-width))/2 - 2.5em) !important;
        min-width: 120px !important;
    }

    .workspace-leaf-content:not(:has(.weekly-note, .monthly-note, .yearly-note)) .nav-link-header-navigation .container {
        display: flex;
        flex-direction: column !important;
        background-color: rgba(255, 255, 255, 0.1) !important;
        border: 0px !important;
        
        .annotated-link {
            max-width: 200px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);

            a {
                margin-right: 0.5em !important;
            }
        }
    }
}

/* Common styles for all screen sizes */
.workspace-leaf-content:not(:has(.weekly-note, .monthly-note, .yearly-note)) .nav-link-header-navigation .container {
    padding: 2px !important;
    background-color: rgba(255, 255, 255, 0.8) !important;
    backdrop-filter: blur(3px);

    .annotated-link {
        padding: 4px !important;
        margin: 4px !important;
        margin-left: 0.5em !important;
        border: 0px !important;
    }
}
```
